# Generated by Django 2.2.3 on 2019-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakeapp', '0004_auto_20190806_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='hostcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='host',
            name='state',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
