# Generated by Django 2.2.3 on 2019-08-06 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wakeapp', '0005_auto_20190806_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='last_online',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='hostcategory',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
