export const GET_HOSTS = "GET_HOSTS";
export const ADD_HOST = "ADD_HOST";
export const DELETE_HOST = "DELETE_HOST";
export const UPDATE_HOST = "UPDATE_HOST";
export const GET_HOST_CATEGORIES = "GET_HOST_CATEGORIES";
export const ADD_HOST_CATEGORY = "ADD_HOST_CATEGORY";
export const DELETE_HOST_CATEGORY = "DELETE_HOST_CATEGORY";
export const UPDATE_HOST_CATEGORY = "UPDATE_HOST_CATEGORY";
