# Generated by Django 2.2.3 on 2019-08-06 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('mac_address', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('wol_port', models.PositiveIntegerField(default=9)),
                ('state', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(default=django.utils.timezone.now)),
                ('remote_vnc_url', models.URLField(blank=True, null=True)),
                ('remote_teamviewer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_splahstop_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wakeapp.HostCategory')),
            ],
        ),
    ]
