# Generated by Django 2.2.3 on 2019-08-06 11:11

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcategory',
            name='color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
        ),
    ]
